### PR TITLE
add scalyr logfiles to scalyr config

### PR DESCRIPTION
**Pull request by astarnell**
add the scalyr logfiles to the scalyr config if it is the scalyr-agent container

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
You're having here two log-config sections for "logging-agent", right? Is it what you want to have?

**Comment by astarnell** [comment]
> You're having here two log-config sections for "logging-agent", right? Is it what you want to have?

For the application "logging-agent" we have 4 sections. One for every container (log-watcher, scalyr-agent, fluentd) with the default k8s stdout logging and one additional section for the scalyr logfile in the scalyr-agent container with the same meta data as the other scalyr-agent section. In scalyr you can distinguish them by their logfile path.

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by astarnell** [comment]
:+1:

**Pull request merged**
