### PR TITLE
Improve log message on errors when parsing annotations

### PR DESCRIPTION
**Pull request by astarnell**
- Add container_name and pod_name to log message
- Only except relevant exception

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
What if some another unexpected exception appears? Entire logwatcher will crash?

**Comment by astarnell** [comment]
> What if some another unexpected exception appears? Entire logwatcher will crash?

In the call hierarchy there is another generall exception handler:
https://github.com/zalando-incubator/kubernetes-log-watcher/blob/b69a28c18edf8cc245b0b1bb93580f6e89e08607/kube_log_watcher/main.py#L160-L169

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by astarnell** [comment]
:+1:

**Comment by astarnell** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
:+1:

**Pull request merged**
