### PR TITLE
Update Docker image

### PR DESCRIPTION
**Pull request by femueller**
Updating Docker image to compliant version `registry.opensource.zalan.do/library/python-3.8-slim:3.8-slim-20201005`.

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by femueller** [comment]
Now we can merge @anton-ryzhov :)

**Comment by femueller** [comment]
:+1:

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by femueller** [comment]
:+1:

**Review by anton-ryzhov — APPROVED** [review]

**Comment by mohabusama** [comment]
👍

**Comment by femueller** [comment]
:+1:

**Review by vwiessner — APPROVED** [review]
lgtm

**Comment by femueller** [comment]
:+1:

**Comment by femueller** [comment]
:+1:

**Comment by vwiessner** [comment]
:+1:

**Pull request merged**
