### PR TITLE
Remove the fallback to set application to pod name if no application label is set

### PR DESCRIPTION
**Pull request by astarnell**
This fallback creates to many distinct applications for reportings.

### CODE REVIEW

**Comment by anton-ryzhov** [comment]
Do we want to define empty app name or don't define it at all?

**Comment by anton-ryzhov** [comment]
Also it may break s3 shipping with paths like `foo//bar` where it was `foo/{appplication}/bar`…

**Comment by anton-ryzhov** [comment]
:-1:

**Comment by astarnell** [comment]
To scalyr we don't send empty attributes. So "empty == not defined" in this case.
For fluentd / S3 shipping we need some value to avoid a ...//... path. The symlinker agent now use "none" as default for application and component.

**Comment by anton-ryzhov** [comment]
:+1:

**Comment by astarnell** [comment]
> Let's use something like `__none` to make clear it's a special value.

I used `none` because the fallback for `version` already uses this and i want to keep it consistently.

**Comment by astarnell** [comment]
On Playground:
```
$ aws s3 ls s3://zalando-logging-407797183256-eu-central-1/kubernetes/none/none/default/test/none/main/2020/01/10/13/        
                           PRE chnguyen/
                           PRE khanchar/
                           PRE piotr/
                           PRE pkmita/
                           PRE rohini/
                           PRE rohinitest/
                           PRE schilukuri/
                           PRE thdang/
                           PRE tkhan/
```

**Comment by astarnell** [comment]
:+1:

**Pull request merged**
